server:
  port: 9201
service-url:
  user_service: http://localhost:8201
spring:
  cloud:
    gateway:
      routes:
        - id: circuitbreaker_route
          uri: ${service-url.user-service}/user/{id}
          filters:
            - CircuitBreaker=myCircuitBreaker